server:
  port: 7004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:7005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://patient-service:7001
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation #Spring will now look for the custom filter with this prefix (check filter package)

        - id: patient-api-docs-route
          uri: http://patient-service:7001
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:7005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

