name: API Gateway process pipeline

on:
  push:
    paths:
      - 'api-gateway/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'api-gateway/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build api-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven package
        working-directory: api-gateway
        run: mvn -B clean package -DskipTests

      # Optional: dependency graph (only if this module uses Maven and the plugin)
      - name: Update dependency graph
        working-directory: api-gateway
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph

  docker:
    name: Build & Push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: api-gateway
          file: api-gateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:cache
          cache-to: type=inline
