name: Billing service process pipeline

on:
  push:
    paths:
      - 'billing-service/**'
      - '.github/workflows/billing-service-pipeline.yml'
  pull_request:
    paths:
      - 'billing-service/**'
      - '.github/workflows/billing-service-pipeline.yml'

jobs:
  build:
    name: Build billing-service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven package
        working-directory: billing-service
        run: mvn -B clean package -DskipTests

      # Optional: dependency graph (only if this module uses Maven and the plugin)
      - name: Update dependency graph
        working-directory: billing-service
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph

  docker:
    name: Build & Push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: billing-service
          file: billing-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/billing-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/billing-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/billing-service:cache
          cache-to: type=inline
